### ISSUE TITLE
Homework #1

### ISSUE THREAD

**Issue by intrueder** [ZoeOstapiuk/KottansHomeworks#1]
Please take a look at the readme in the following repository: https://github.com/intrueder/CitizenRegistry/tree/master

**Comment by ZoeOstapiuk** [comment]
https://github.com/ZoeOstapiuk/CitizenRegistry

**Comment by ZoeOstapiuk** [comment]
I fixed problems and added few tests to check ID's validity :) 
https://github.com/ZoeOstapiuk/CitizenRegistry/commit/c58ac3ceeda6d40cf359ef180f89ccde5c62c3ee

**Comment by ZoeOstapiuk** [comment]
Thank you for reviewing, I optimized loops and changed few details:)
https://github.com/ZoeOstapiuk/CitizenRegistry/commit/8fc9c7cca818770c1c421b189d08c5e324c89907

**Comment by intrueder** [comment]
Great job! :+1:
